spring:
  application:
    name: studyBoard
  datasource:
    url: jdbc:mysql://localhost:3306/studycrewdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: passwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: trace
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  jwt:
    secret: vmfhasdffwefsdffkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb